package edu.calvin.cs262.ajf27.hw2;


import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v7.preference.PreferenceFragmentCompat;

/**
 * Settings Fragment displayes the app's single dummy preference.
 *
 * @author Littlesnowman88
 */
public class SettingsFragment extends PreferenceFragmentCompat {

    /**
     * SettingsFragment() is a required empty public constructor generated by Android Studio.
     */
    public SettingsFragment() {
        // Required empty public constructor
    }

    /**
     * onCreatePreferences grabs app preferences (settings) from preferences.xml and displays them on the screen
     *
     * @param savedInstanceState the last known state of the SettingsFragment screen
     * @param rootKey            generated by Android, I'm not sure what this does.
     * @author Littlesnowman88
     * @author AndroidStudio
     */
    @Override
    public void onCreatePreferences(Bundle savedInstanceState,
                                    String rootKey) {
        setPreferencesFromResource(R.xml.preferences, rootKey);
    }

}
